=head1 Book::BestOfCPAN::Preface

The source of this book is available on GitHub


=head1 COPYRIGHT & LICENSE

Copyright 2010 SE<eacute>bastien Aperghis-Tramoni, all rights reserved.

This software and associated documentation are free software; you can
redistribute it and/or modify it under the same terms as Perl itself.

